"""
GFEM BDF Combination Tool
Reads a Combination Excel, finds unit case BDF files via a List Subcases mapping Excel,
and writes a master BDF with INCLUDE statements (deduplicated).
"""
from __future__ import annotations

import os
import queue
import threading
from datetime import datetime
from pathlib import Path
import tkinter as tk
from tkinter import filedialog, messagebox, scrolledtext, ttk

try:
    import pandas as pd
except ImportError:
    messagebox.showerror(
        "Missing Dependency",
        "pandas is not installed.\nRun: pip install pandas openpyxl",
    )
    raise SystemExit(1)


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------

def read_case_ids_from_excel(excel_path: str, log_fn=None) -> set[int]:
    """Return unique non-zero integer case IDs from all *CASE ID columns excluding THERMAL."""
    if log_fn:
        log_fn("[EXCEL] Reading Combination Excel...")
    df = pd.read_excel(excel_path, engine="openpyxl")

    case_id_cols = [
        col for col in df.columns
        if "CASE ID" in str(col).upper() and "THERMAL" not in str(col).upper()
    ]
    if log_fn:
        log_fn(f"[EXCEL] Unit case columns ({len(case_id_cols)}): {', '.join(str(c) for c in case_id_cols)}")

    ids: set[int] = set()
    for col in case_id_cols:
        for val in df[col].dropna():
            try:
                int_val = int(val)
                if int_val != 0:
                    ids.add(int_val)
            except (ValueError, TypeError):
                pass
    return ids


def read_subcase_mapping(list_excel_path: str, log_fn=None) -> dict[int, str]:
    """
    Read the List Subcases Excel.
    Expects column A = FILE (relative path), column B = SUBCASE_ID.
    Returns {subcase_id: relative_file_path}.
    """
    if log_fn:
        log_fn("[SUBCASES] Reading List Subcases Excel...")
    df = pd.read_excel(list_excel_path, engine="openpyxl")

    # Normalise column names — use positional fallback if headers differ
    cols = list(df.columns)
    file_col = cols[0]
    id_col = cols[1]
    if log_fn:
        log_fn(f"[SUBCASES] Using columns: FILE='{file_col}', SUBCASE_ID='{id_col}'")

    mapping: dict[int, str] = {}
    for _, row in df.iterrows():
        try:
            sid = int(row[id_col])
            fpath = str(row[file_col]).strip()
            mapping[sid] = fpath
        except (ValueError, TypeError):
            pass

    if log_fn:
        log_fn(f"[SUBCASES] {len(mapping)} subcase → file mappings loaded.")
    return mapping


def resolve_include_paths(
    case_ids: set[int],
    subcase_mapping: dict[int, str],
    base_dir: str,
    log_fn=None,
) -> tuple[list[str], list[int]]:
    """
    For each case ID, look up the relative path and resolve against base_dir.
    Returns (ordered_unique_paths, missing_ids).
    Preserves first-seen order; duplicates are dropped.
    """
    seen: set[str] = set()
    ordered_paths: list[str] = []
    missing_ids: list[int] = []

    for cid in sorted(case_ids):
        if cid not in subcase_mapping:
            missing_ids.append(cid)
            if log_fn:
                log_fn(f"[ERROR] Case ID {cid} not found in List Subcases Excel.")
            continue

        rel = subcase_mapping[cid].lstrip("\\/")
        full_path = os.path.join(base_dir, rel)
        norm = os.path.normpath(full_path)

        if norm not in seen:
            seen.add(norm)
            ordered_paths.append(norm)
            if log_fn:
                log_fn(f"[OK]    {cid} → {norm}")
        else:
            if log_fn:
                log_fn(f"[DUP]   {cid} → already included ({os.path.basename(norm)}), skipped.")

    return ordered_paths, missing_ids


def write_output_bdf(
    gfem_path: str,
    include_paths: list[str],
    output_path: str,
    log_fn=None,
) -> int:
    """Write the master BDF with INCLUDE statements. Returns total INCLUDE count."""
    lines = []
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines.append("$ Generated by GFEM BDF Combination Tool")
    lines.append(f"$ Date: {timestamp}")
    lines.append("$")
    lines.append("$ GFEM Model")
    lines.append(f"INCLUDE '{gfem_path}'")
    lines.append("$")
    lines.append("$ Unit Case Loads")

    for p in include_paths:
        lines.append(f"INCLUDE '{p}'")

    lines.append("$")
    lines.append("$ END")

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    include_count = 1 + len(include_paths)  # 1 for GFEM
    if log_fn:
        log_fn(f"[WRITE] {output_path}  ({include_count} INCLUDE lines total)")
    return include_count


# ---------------------------------------------------------------------------
# GUI
# ---------------------------------------------------------------------------

class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("GFEM BDF Combination Tool")
        self.resizable(True, True)
        self._log_queue: queue.Queue = queue.Queue()
        self._status_queue: queue.Queue = queue.Queue()
        self._build_ui()
        self.after(100, self._poll_queues)

    def _build_ui(self):
        pad = {"padx": 8, "pady": 4}
        frame = ttk.Frame(self, padding=10)
        frame.grid(row=0, column=0, sticky="nsew")
        self.columnconfigure(0, weight=1)
        self.rowconfigure(0, weight=1)
        frame.columnconfigure(1, weight=1)

        fields = [
            ("GFEM BDF File:",        "gfem_var",    self._browse_gfem),
            ("Combination Excel:",    "excel_var",   self._browse_excel),
            ("List Subcases Excel:",  "subcases_var", self._browse_subcases),
            ("Unit Case Base Dir:",   "dir_var",     self._browse_dir),
            ("Output BDF:",           "output_var",  self._browse_output),
        ]
        for row, (label, attr, cmd) in enumerate(fields):
            ttk.Label(frame, text=label).grid(row=row, column=0, sticky="e", **pad)
            var = tk.StringVar()
            setattr(self, attr, var)
            entry = ttk.Entry(frame, textvariable=var, width=60)
            entry.grid(row=row, column=1, sticky="ew", **pad)
            ttk.Button(frame, text="Browse", command=cmd).grid(row=row, column=2, **pad)

        self._gen_btn = ttk.Button(frame, text="Generate BDF", command=self._on_generate)
        self._gen_btn.grid(row=len(fields), column=0, columnspan=3, pady=10)

        self._progress = ttk.Progressbar(frame, mode="indeterminate")
        self._progress.grid(row=len(fields) + 1, column=0, columnspan=3, sticky="ew", padx=8)

        self._status_var = tk.StringVar(value="Ready.")
        ttk.Label(
            frame, textvariable=self._status_var,
            foreground="#005580", font=("Courier", 8), anchor="w"
        ).grid(row=len(fields) + 2, column=0, columnspan=3, sticky="ew", padx=8, pady=(2, 0))

        ttk.Label(frame, text="Log:").grid(row=len(fields) + 3, column=0, sticky="w", padx=8)
        self._log_widget = scrolledtext.ScrolledText(
            frame, height=18, state="disabled", wrap="word", font=("Courier", 8)
        )
        self._log_widget.grid(
            row=len(fields) + 4, column=0, columnspan=3, sticky="nsew", padx=8, pady=4
        )
        frame.rowconfigure(len(fields) + 4, weight=1)

    # --- Browse helpers ---

    def _browse_gfem(self):
        p = filedialog.askopenfilename(
            title="Select GFEM BDF File",
            filetypes=[("BDF files", "*.bdf *.BDF"), ("All files", "*.*")],
        )
        if p:
            self.gfem_var.set(p)

    def _browse_excel(self):
        p = filedialog.askopenfilename(
            title="Select Combination Excel",
            filetypes=[("Excel files", "*.xlsx *.xls"), ("All files", "*.*")],
        )
        if p:
            self.excel_var.set(p)

    def _browse_subcases(self):
        p = filedialog.askopenfilename(
            title="Select List Subcases Excel",
            filetypes=[("Excel files", "*.xlsx *.xls"), ("All files", "*.*")],
        )
        if p:
            self.subcases_var.set(p)

    def _browse_dir(self):
        p = filedialog.askdirectory(title="Select Unit Case Base Directory")
        if p:
            self.dir_var.set(p)

    def _browse_output(self):
        p = filedialog.asksaveasfilename(
            title="Save Output BDF As",
            defaultextension=".bdf",
            filetypes=[("BDF files", "*.bdf"), ("All files", "*.*")],
        )
        if p:
            self.output_var.set(p)

    # --- Generate ---

    def _on_generate(self):
        gfem      = self.gfem_var.get().strip()
        excel     = self.excel_var.get().strip()
        subcases  = self.subcases_var.get().strip()
        base_dir  = self.dir_var.get().strip()
        output    = self.output_var.get().strip()

        errors = []
        if not gfem or not os.path.isfile(gfem):
            errors.append("GFEM BDF file not found.")
        if not excel or not os.path.isfile(excel):
            errors.append("Combination Excel file not found.")
        if not subcases or not os.path.isfile(subcases):
            errors.append("List Subcases Excel file not found.")
        if not base_dir or not os.path.isdir(base_dir):
            errors.append("Unit case base directory not found.")
        if not output:
            errors.append("Please specify an output BDF path.")
        if errors:
            messagebox.showerror("Input Error", "\n".join(errors))
            return

        self._gen_btn.configure(state="disabled")
        self._progress.start(10)

        threading.Thread(
            target=self._run_generation,
            args=(gfem, excel, subcases, base_dir, output),
            daemon=True,
        ).start()

    def _run_generation(self, gfem, excel, subcases, base_dir, output):
        try:
            self._status("Reading Combination Excel...")
            case_ids = read_case_ids_from_excel(excel, log_fn=self._log)
            self._log(f"[INFO] {len(case_ids)} unique case IDs (thermal excluded).")

            self._status("Reading List Subcases Excel...")
            subcase_mapping = read_subcase_mapping(subcases, log_fn=self._log)

            self._status("Resolving file paths...")
            self._log("-" * 60)
            include_paths, missing = resolve_include_paths(
                case_ids, subcase_mapping, base_dir, log_fn=self._log
            )
            self._log("-" * 60)

            self._log(
                f"[INFO] {len(include_paths)} unique files to include. "
                f"{len(missing)} IDs not found in subcases list."
            )

            if missing:
                self._log(f"[ERROR] Missing IDs: {sorted(missing)}")

            self._status("Writing output BDF...")
            write_output_bdf(gfem, include_paths, output, log_fn=self._log)
            self._log("[DONE] Generation complete.")
            self._status("Done.")

        except Exception as exc:
            self._log(f"[ERROR] {exc}")
            self._status(f"ERROR: {exc}")
            self.after(0, lambda: messagebox.showerror("Error", str(exc)))
        finally:
            self.after(0, self._generation_done)

    def _generation_done(self):
        self._progress.stop()
        self._gen_btn.configure(state="normal")

    # --- Thread-safe log & status ---

    def _log(self, msg: str):
        self._log_queue.put(msg + "\n")

    def _status(self, msg: str):
        self._status_queue.put(msg)

    def _log_write(self, msg: str):
        self._log_widget.configure(state="normal")
        self._log_widget.insert(tk.END, msg)
        self._log_widget.see(tk.END)
        self._log_widget.configure(state="disabled")

    def _poll_queues(self):
        while not self._log_queue.empty():
            self._log_write(self._log_queue.get_nowait())
        while not self._status_queue.empty():
            self._status_var.set(self._status_queue.get_nowait())
        self.after(100, self._poll_queues)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    app = App()
    app.mainloop()
