"""
GFEM BDF Combination Tool
Reads a Combination Excel, finds unit case BDF files, and writes a master BDF with INCLUDE statements.
"""
from __future__ import annotations

import os
import queue
import threading
from datetime import datetime
from pathlib import Path
import tkinter as tk
from tkinter import filedialog, messagebox, scrolledtext, ttk

try:
    import pandas as pd
except ImportError:
    messagebox.showerror(
        "Missing Dependency",
        "pandas is not installed.\nRun: pip install pandas openpyxl",
    )
    raise SystemExit(1)


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------

def read_case_ids_from_excel(excel_path: str, log_fn=None) -> set[int]:
    """Return unique non-zero integer case IDs from all *CASE ID columns excluding THERMAL."""
    if log_fn:
        log_fn("[EXCEL] Reading Excel file (this may take a moment)...")
    df = pd.read_excel(excel_path, engine="openpyxl")

    case_id_cols = [
        col for col in df.columns
        if "CASE ID" in str(col).upper() and "THERMAL" not in str(col).upper()
    ]
    if log_fn:
        log_fn(f"[EXCEL] Columns found ({len(case_id_cols)}): {', '.join(str(c) for c in case_id_cols)}")

    ids: set[int] = set()
    for col in case_id_cols:
        for val in df[col].dropna():
            try:
                int_val = int(val)
                if int_val != 0:
                    ids.add(int_val)
            except (ValueError, TypeError):
                pass
    return ids


def find_bdf_files_for_ids(
    search_dir: str,
    case_ids: set[int],
    log_fn=None,
    status_fn=None,
) -> dict[int, list[Path]]:
    """Recursively find BDF files whose names contain each case ID."""
    result: dict[int, list[Path]] = {cid: [] for cid in case_ids}
    str_ids = {cid: str(cid) for cid in case_ids}

    total_scanned = 0
    total_matched = 0
    dir_count = 0

    for root, _dirs, files in os.walk(search_dir):
        dir_count += 1
        short_root = root if len(root) <= 80 else "..." + root[-77:]
        if status_fn:
            status_fn(f"[{dir_count} dirs]  {short_root}")
        if log_fn:
            log_fn(f"[SCAN] ({dir_count}) {root}")

        for fname in files:
            if not fname.lower().endswith(".bdf"):
                continue
            total_scanned += 1
            for cid, sid in str_ids.items():
                if sid in fname:
                    result[cid].append(Path(root) / fname)
                    total_matched += 1

    if log_fn:
        log_fn(
            f"[SCAN] Done. {dir_count} dirs | {total_scanned} BDF files scanned | {total_matched} matches."
        )
    if status_fn:
        status_fn("Scan complete.")
    return result


def write_output_bdf(
    gfem_path: str,
    files_by_id: dict[int, list[Path]],
    output_path: str,
    log_fn=None,
) -> int:
    """Write the master BDF with INCLUDE statements. Returns total INCLUDE count."""
    include_count = 0
    lines = []

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines.append("$ Generated by GFEM BDF Combination Tool")
    lines.append(f"$ Date: {timestamp}")
    lines.append("$")
    lines.append("$ GFEM Model")
    lines.append(f"INCLUDE '{gfem_path}'")
    include_count += 1
    lines.append("$")
    lines.append("$ Unit Case Loads")

    for cid in sorted(files_by_id):
        paths = sorted(files_by_id[cid])
        if not paths:
            continue
        lines.append(f"$ --- Case ID: {cid} ---")
        for p in paths:
            lines.append(f"INCLUDE '{p}'")
            include_count += 1

    lines.append("$")
    lines.append("$ END")

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    if log_fn:
        log_fn(f"[WRITE] Output written: {output_path}  ({include_count} INCLUDE lines total)")
    return include_count


# ---------------------------------------------------------------------------
# GUI
# ---------------------------------------------------------------------------

class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("GFEM BDF Combination Tool")
        self.resizable(True, True)
        self._log_queue: queue.Queue = queue.Queue()
        self._status_queue: queue.Queue = queue.Queue()
        self._build_ui()
        self.after(100, self._poll_queues)

    def _build_ui(self):
        pad = {"padx": 8, "pady": 4}
        frame = ttk.Frame(self, padding=10)
        frame.grid(row=0, column=0, sticky="nsew")
        self.columnconfigure(0, weight=1)
        self.rowconfigure(0, weight=1)
        frame.columnconfigure(1, weight=1)

        # --- Input rows ---
        fields = [
            ("GFEM BDF File:",     "gfem_var",   self._browse_gfem),
            ("Combination Excel:", "excel_var",  self._browse_excel),
            ("Unit Case Dir:",     "dir_var",    self._browse_dir),
            ("Output BDF:",        "output_var", self._browse_output),
        ]
        for row, (label, attr, cmd) in enumerate(fields):
            ttk.Label(frame, text=label).grid(row=row, column=0, sticky="e", **pad)
            var = tk.StringVar()
            setattr(self, attr, var)
            entry = ttk.Entry(frame, textvariable=var, width=60)
            entry.grid(row=row, column=1, sticky="ew", **pad)
            ttk.Button(frame, text="Browse", command=cmd).grid(row=row, column=2, **pad)

        # --- Generate button ---
        self._gen_btn = ttk.Button(
            frame, text="Generate BDF", command=self._on_generate
        )
        self._gen_btn.grid(row=4, column=0, columnspan=3, pady=10)

        # --- Progress bar ---
        self._progress = ttk.Progressbar(frame, mode="indeterminate")
        self._progress.grid(row=5, column=0, columnspan=3, sticky="ew", padx=8)

        # --- Live status label ---
        self._status_var = tk.StringVar(value="Ready.")
        status_label = ttk.Label(
            frame, textvariable=self._status_var,
            foreground="#005580", font=("Courier", 8), anchor="w"
        )
        status_label.grid(row=6, column=0, columnspan=3, sticky="ew", padx=8, pady=(2, 0))

        # --- Log area ---
        ttk.Label(frame, text="Log:").grid(row=7, column=0, sticky="w", padx=8)
        self._log_widget = scrolledtext.ScrolledText(
            frame, height=18, state="disabled", wrap="word", font=("Courier", 8)
        )
        self._log_widget.grid(row=8, column=0, columnspan=3, sticky="nsew", padx=8, pady=4)
        frame.rowconfigure(8, weight=1)

    # --- Browse helpers ---

    def _browse_gfem(self):
        p = filedialog.askopenfilename(
            title="Select GFEM BDF File",
            filetypes=[("BDF files", "*.bdf *.BDF"), ("All files", "*.*")],
        )
        if p:
            self.gfem_var.set(p)

    def _browse_excel(self):
        p = filedialog.askopenfilename(
            title="Select Combination Excel",
            filetypes=[("Excel files", "*.xlsx *.xls"), ("All files", "*.*")],
        )
        if p:
            self.excel_var.set(p)

    def _browse_dir(self):
        p = filedialog.askdirectory(title="Select Unit Case BDF Search Directory")
        if p:
            self.dir_var.set(p)

    def _browse_output(self):
        p = filedialog.asksaveasfilename(
            title="Save Output BDF As",
            defaultextension=".bdf",
            filetypes=[("BDF files", "*.bdf"), ("All files", "*.*")],
        )
        if p:
            self.output_var.set(p)

    # --- Generate ---

    def _on_generate(self):
        gfem = self.gfem_var.get().strip()
        excel = self.excel_var.get().strip()
        search_dir = self.dir_var.get().strip()
        output = self.output_var.get().strip()

        errors = []
        if not gfem or not os.path.isfile(gfem):
            errors.append("GFEM BDF file not found.")
        if not excel or not os.path.isfile(excel):
            errors.append("Combination Excel file not found.")
        if not search_dir or not os.path.isdir(search_dir):
            errors.append("Unit case search directory not found.")
        if not output:
            errors.append("Please specify an output BDF path.")
        if errors:
            messagebox.showerror("Input Error", "\n".join(errors))
            return

        self._gen_btn.configure(state="disabled")
        self._progress.start(10)

        thread = threading.Thread(
            target=self._run_generation,
            args=(gfem, excel, search_dir, output),
            daemon=True,
        )
        thread.start()

    def _run_generation(self, gfem, excel, search_dir, output):
        try:
            self._status("Reading Excel...")
            case_ids = read_case_ids_from_excel(excel, log_fn=self._log)
            self._log(f"[INFO] {len(case_ids)} unique case IDs found (thermal excluded).")
            self._status(f"{len(case_ids)} case IDs found. Starting directory scan...")

            files_by_id = find_bdf_files_for_ids(
                search_dir, case_ids, log_fn=self._log, status_fn=self._status
            )

            found_count = sum(1 for v in files_by_id.values() if v)
            not_found_ids = sorted(cid for cid, v in files_by_id.items() if not v)

            self._log("-" * 60)
            for cid in sorted(files_by_id):
                paths = files_by_id[cid]
                if paths:
                    self._log(f"[OK]   {cid} → {len(paths)} file(s)")
                else:
                    self._log(f"[WARN] {cid} → no files found")
            self._log("-" * 60)

            self._log(
                f"[INFO] {found_count}/{len(case_ids)} IDs matched. "
                f"{len(not_found_ids)} IDs had no match."
            )
            self._status("Writing output BDF...")
            self._log("[INFO] Writing output BDF...")
            write_output_bdf(gfem, files_by_id, output, log_fn=self._log)
            self._log("[DONE] Generation complete.")
            self._status("Done.")

        except Exception as exc:
            self._log(f"[ERROR] {exc}")
            self._status(f"ERROR: {exc}")
            self.after(0, lambda: messagebox.showerror("Error", str(exc)))
        finally:
            self.after(0, self._generation_done)

    def _generation_done(self):
        self._progress.stop()
        self._gen_btn.configure(state="normal")

    # --- Thread-safe log & status ---

    def _log(self, msg: str):
        self._log_queue.put(msg + "\n")

    def _status(self, msg: str):
        self._status_queue.put(msg)

    def _log_write(self, msg: str):
        self._log_widget.configure(state="normal")
        self._log_widget.insert(tk.END, msg)
        self._log_widget.see(tk.END)
        self._log_widget.configure(state="disabled")

    def _poll_queues(self):
        while not self._log_queue.empty():
            self._log_write(self._log_queue.get_nowait())
        while not self._status_queue.empty():
            self._status_var.set(self._status_queue.get_nowait())
        self.after(100, self._poll_queues)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    app = App()
    app.mainloop()
